# Generated by Django 2.0.4 on 2018-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitaji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
